### ISSUE TITLE
Handle long named PVs better

### ISSUE THREAD

**Issue by nikdoof** [replicatedhq/pvmigrate#155]
kube-prometheus-stack Helm chart produces some stupid naming conventions, that fly very close to the sun regarding name length. Running `pvmigrate` throws an error as the new PVC name goes over the max length.

It would be a nice to have for pvmigrate to handle these situations and maybe derive a shorter name for the migration PVC

```
Running pvmigrate build:
version=v0.8.0-dirty
sha=33bbb070fd5685c16b544c84f7ec8e7398c8164d
time=2023-02-25T11:48:51Z

...

Found 1 matching PVCs to migrate across 1 namespaces:
namespace: pvc:                                                                                         pv:                                      size:
prometheus prometheus-kube-prometheus-stack-prometheus-db-prometheus-kube-prometheus-stack-prometheus-0 pvc-24dd3b63-f891-413c-9a33-3acaefe5c0e0 20Gi
prometheus kube-prometheus-stack-grafana                                                                pvc-aa1153a7-dc83-445e-95fa-4eaf87eeffd4 250Mi
prometheus prometheus-kube-prometheus-stack-prometheus-db-prometheus-kube-prometheus-stack-prometheus-1 pvc-fcf77baf-7c4f-4be9-916f-0206dd7e0392 500Gi

Creating new PVCs to migrate data to using the nfs-client-standard StorageClass
migration failed: failed to create new PVC prometheus-kube-prometheus-stacus-stack-prometheus-0-pvcmigrate in prometheus: PersistentVolumeClaim "prometheus-kube-prometheus-stacus-stack-prometheus-0-pvcmigrate" is invalid: metadata.labels: Invalid value: "prometheus-kube-prometheus-stack-prometheus-db-prometheus-kube-prometheus-stack-prometheus-0": must be no more than 63 characters
```

**Comment by czomo** [comment]
We also facing the same issue with prometheus😭

**Comment by nikdoof** [comment]
I just noticed after looking how to potentially fix this that it should already do this:

https://github.com/replicatedhq/pvmigrate/blob/33bbb070fd5685c16b544c84f7ec8e7398c8164d/pkg/migrate/migrate.go#L590

**Comment by laverya** [comment]
@nikdoof That _should_ have been the case since the very first release of pvmigrate - do you have an example of a PVC name that is failing?

**Comment by czomo** [comment]
@laverya 
It would be enough?
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: ebs.csi.aws.com
    volume.kubernetes.io/storage-provisioner: ebs.csi.aws.com
  labels:
    app.kubernetes.io/instance: prometheus-prometheus
    app.kubernetes.io/managed-by: prometheus-operator
    app.kubernetes.io/name: prometheus
    operator.prometheus.io/name: prometheus-prometheus
    operator.prometheus.io/shard: "0"
    prometheus: prometheus-prometheus
  name: prometheus-prometheus-prometheus-db-prometheus-prometheus-prometheus-0
  namespace: monitoring
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp2
  volumeName: pvc-xx-xx-xx-xxx-XXXXXX
```
