### ISSUE TITLE
"Object is being deleted" Error during migration

### ISSUE THREAD

**Issue by DanStough** [replicatedhq/pvmigrate#56]
# Description
When trying to migrate from Rook to Longhorn, I get the following error which looks like a race condition in deleting the PVC and re-creating:
```
Swapping PVC kotsadm-postgres-kotsadm-postgres-0 in default to the new StorageClass
Marking original PV pvc-307e0664-39e9-4153-baf2-6696953401c8 as to-be-retained
Marking migrated-to PV pvc-da1fac2b-13df-46f0-91d3-99b813c379dc as to-be-retained
Deleting original PVC kotsadm-postgres-kotsadm-postgres-0 in default to free up the name
Deleting migrated-to PVC kotsadm-postgres-kotsadm-postgres-0 in default to release the PV
Removing claimref from original PV pvc-307e0664-39e9-4153-baf2-6696953401c8
Removing claimref from migrated-to PV pvc-da1fac2b-13df-46f0-91d3-99b813c379dc
Creating new PVC kotsadm-postgres-kotsadm-postgres-0 with migrated-to PV pvc-da1fac2b-13df-46f0-91d3-99b813c379dc
failed to swap PVs for PVC kotsadm-postgres-kotsadm-postgres-0 in default: failed to create migrated-to PVC kotsadm-postgres-kotsadm-postgres-0 in default: object is being deleted: persistentvolumeclaims "kotsadm-postgres-kotsadm-postgres-0" already exists
```

# How to Repro
Environment: 
Ubuntu 20.04

Used this rook installer as the base: https://kurl.sh/a60de60 

Then tried to migrate to this installer (note that 1.21.8 hasn't been merged yet, but I imagine any 1.21 would produce similar results)
```yaml
apiVersion: cluster.kurl.sh/v1beta1
kind: Installer
metadata: 
  name: latest
spec: 
  kubernetes: 
    version: 1.21.8
  weave: 
    version: 2.6.5
  registry: 
    version: 2.7.1
  containerd: 
    version: 1.4.9
  longhorn:
    version: 1.2.2
  velero:
    version: 1.7.1
  kotsadm:
    version: 1.59.0
    disableS3: true
```

# Suggested Fix:
[This seems to be in the neighborhood of the pending delete](https://github.com/replicatedhq/pvmigrate/blob/f873379191f834583827dc88ddd0af09358752ff/pkg/migrate/migrate.go#L906)
